### ISSUE TITLE
improve field

### ISSUE THREAD

**Issue by okwme** [clovers-network/clovers-dapp#213]
- [ ] make field interactions more fun
- [x]  bigger heart
- [ ]  include symmetry

**Comment by n-kort** [comment]
should also include heart in `KeepClover` component, along with something like 'Copy moves string' so that users can add their faves on a different device (a manual version of #101?).

I guess it's not very clear what's going on in this view, so a dismissible message at the top explaining what happens in the field would be a helpful intro for people.

**Comment by okwme** [comment]
- [ ] allow to hear/unheart from pop-up
- [ ] after keep, make link to "my picks" or to actual clover page
