### ISSUE TITLE
Clovers missing from my profile and user page

### ISSUE THREAD

**Issue by okwme** [clovers-network/clovers-dapp#253]
only shows 7 clovers on https://clovers.network/users/0xfa398d672936dcf428116f687244034961545d91
but if you scroll through the market you can see i own way more

**Comment by n-kort** [comment]
Think this is because the clover list is built from the nested array in the user object, which for some reason is not updated when you buy a thing (and perhaps during other updates too).

In `User.vue` and the `userClovers` getter we're doing a slice -> map -> find -> sort thing, why not just `allClovers.filter(c => c.owner === user.address)`?
